In [55]:
import pandas as pd

Ler fontes de dados oficiais

In [56]:
df_exp = pd.read_csv('databases/govbr/EXP_2025.csv', delimiter=';',encoding='cp1252')

In [57]:
df_ncm = pd.read_csv('databases/govbr/NCM.csv', delimiter=';', encoding='cp1252')

In [58]:
df_pais = pd.read_csv('databases/govbr/PAIS.csv', delimiter=';', encoding='cp1252')

Gerar tabela unificada

In [59]:
DfExportacaoNCM = pd.merge(df_exp, df_ncm[['CO_NCM', 'NO_NCM_POR']],on= 'CO_NCM')

In [60]:
DfExportacaoNCMporPais = pd.merge(DfExportacaoNCM, df_pais[['CO_PAIS', 'NO_PAIS']],on= 'CO_PAIS')

Análise de Principais produtos exportados do Brasil

In [61]:
DfExportacaoValorNCMAgregado = DfExportacaoNCM.groupby(['CO_NCM', 'NO_NCM_POR'])[['VL_FOB']].sum().reset_index()

In [62]:
TotalExportacaoBrasil = DfExportacaoValorNCMAgregado['VL_FOB'].sum()

In [63]:
DfExportacaoValorNCMAgregado['PCT_TOTAL'] = DfExportacaoValorNCMAgregado.apply(lambda row: (row['VL_FOB'] / TotalExportacaoBrasil) * 100, axis=1)

In [64]:
DfExportacaoValorNCMAgregado.sort_values('VL_FOB', ascending=False).head(10)

,CO_NCM,NO_NCM_POR,VL_FOB,PCT_TOTAL
1253,27090010,Óleos brutos de petróleo,44536157927,12.787514
680,12019000,"Soja, mesmo triturada, exceto para semeadura",43531594841,12.499077
1200,26011100,"Minérios de ferro e seus concentrados, exceto ...",26290907269,7.548818
572,9011110,"Café não torrado, não descafeinado, em grão",14865438263,4.268262
33,2023000,"Carnes desossadas de bovino, congeladas",14406299941,4.136431
867,17011400,Outros açúcares de cana,12079891914,3.468458
3611,47032900,"Pastas químicas de madeira, à soda ou ao sulfa...",8939118511,2.566658
628,10059010,"Milho em grão, exceto para semeadura",8449220056,2.425996
1267,27101922,Fuel oil,7006597350,2.011780
1085,23040090,"Bagaços e outros resíduos sólidos, da extração...",5991809310,1.720408

Análise de Principais Destinos de Exportação

In [65]:
DfExportacaoNCMporPais = pd.merge(DfExportacaoNCM, df_pais[['CO_PAIS', 'NO_PAIS']],on= 'CO_PAIS')

In [66]:
RankingPaisesExportacao = DfExportacaoNCMporPais.groupby('NO_PAIS')['VL_FOB'].sum().reset_index()

In [67]:
RankingPaisesExportacao.sort_values('VL_FOB', ascending=False).head(10)

                     NO_PAIS       VL_FOB
45                     China  99940244710
73            Estados Unidos  37682246914
9                  Argentina  18105303283
170  Países Baixos (Holanda)  11726736048
72                   Espanha   8783248496
149                   México   7728866863
195                Singapura   7353096562
39                    Canadá   7251870870
44                     Chile   7176227117
244                    Índia   6865880767

Estudo sobre exportações à Argentina

In [68]:
df_filtrado = DfExportacaoNCMporPais.loc[DfExportacaoNCMporPais['NO_PAIS'] == 'Argentina']

In [69]:
df_filtrado = df_filtrado.groupby(['CO_NCM', 'NO_NCM_POR'])['VL_FOB'].sum().reset_index()

In [70]:
df_filtrado.sort_values('VL_FOB', ascending=False).head(10)

        CO_NCM                                         NO_NCM_POR      VL_FOB
4506  87032210  Automóveis com motor explosão, de cilindrada s...  1297219314
4505  87032100  Automóveis com motor explosão, de cilindrada n...  1196763171
4508  87032310  Automóveis com motor explosão, 1500 < cm3 <= 3...   988794711
4498  87012100  Tratores rodoviários para semirreboques, unica...   873054728
4520  87043190  Outros veículos automóveis com motor a explosã...   536146431
579   27160000                                   Energia elétrica   293496580
4517  87042210  Chassis com motor diesel e cabina, 5 toneladas...   249172606
4516  87042190  Outros veículos automóveis com motor diesel, p...   228895474
4575  87089990  Outras partes e acessórios para tratores e veí...   227721104
4512  87034000  Outros veículos, equipados para propulsão, sim...   204235250